import React from "react"
import Head from "next/head"
import { useRouter } from "next/router"
import { Container, Row, Col } from "react-bootstrap"
import Headline from "../../components/Headline"
import Footer from "../../components/Footer"

export default function Server() {
    const router = useRouter()
    const { server } = router.query

    return (
        <div id="root">
            <Head>
                <title>Browsing {server}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="main">
                <Container>
                    <Row>
                        <Col lg={12}>
                            <Headline title="World of Wallstreet" subtitle={`Listed items from ${server}`} />
                        </Col>
                    </Row>
                </Container>
            </main>
            <Footer />
        </div>
    )
}
